[package]
name = "ecs"
version = "0.1.0"
edition = "2021"

# the ecs host is linked statically into each plugin which runs it with `hotline_ecs_plugin!`, so the host and the
# systems it runs are compiled together and agree on bevy TypeIds
[lib]
crate-type = ["rlib"]

[dependencies]
hotline-rs.workspace = true
maths-rs.workspace = true
bevy_ecs.workspace = true
serde.workspace = true
serde_json.workspace = true
font-awesome.workspace = true
bitflags.workspace = true
