name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  win32:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: "recursive"
    - name: build-data
      run: |
        cargo build
        hotline-data\\pmbuild.cmd win32-debug -all
    - name: tests
      run: |
        hotline-data\\pmbuild.cmd test