name: tests
on: [push, pull_request]
jobs:
  win32:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
        .\\hotline-data\\pmbuild.cmd win32-debug -all
        cargo test -- --test-threads 1